version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules # Avoid mixing files
    ports:
      - "3000:3000"
    #environment:
      #- VIRTUAL_HOST=solidarite.ponsaille.com
      #- LETSENCRYPT_HOST=solidarite.ponsaille.com
      #- LETSENCRYPT_EMAIL=jules.ponsaille@gmail.com
  
  mysql:
    image: mysql
    restart: always
    volumes:
      - /var/lib/mysql # Persist database
    environment:
      - MYSQL_DATABASE=ndi
      - MYSQL_ROOT_PASSWORD=devpass

#networks:
#  default:
#    external:
#      name: nginx-proxy
